/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    classes: Class;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    classes: ClassesSelect<false> | ClassesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Manage the class cards shown in the Our Classes section. Add, delete, reorder, and change images here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes".
 */
export interface Class {
  id: string;
  name: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short text used on the class card overlay.
   */
  excerpt?: string | null;
  image?: (string | null) | Media;
  /**
   * Lower numbers appear first on the website.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage website images and uploaded files used by the landing page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'classes';
        value: string | Class;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classes_select".
 */
export interface ClassesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  excerpt?: T;
  image?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Edit the full single-page website: navigation, hero, benefits, classes intro, contact section, and footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: string;
  navbar?: {
    logo?: (string | null) | Media;
    links?:
      | {
          label: string;
          page: 'home' | 'benefits' | 'ourclasses' | 'contactus';
          id?: string | null;
        }[]
      | null;
    signInLabel?: string | null;
    ctaLabel?: string | null;
  };
  home?: {
    headlineImage?: (string | null) | Media;
    body?: string | null;
    primaryCtaLabel?: string | null;
    secondaryCtaLabel?: string | null;
    heroImage?: (string | null) | Media;
    sponsors?:
      | {
          name: string;
          logo: string | Media;
          id?: string | null;
        }[]
      | null;
  };
  benefits?: {
    heading?: string | null;
    intro?: string | null;
    /**
     * Add, remove, and reorder benefit cards displayed under the intro.
     */
    cards?:
      | {
          icon?: ('building' | 'group' | 'academic') | null;
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    cardCtaLabel?: string | null;
    featureImage?: (string | null) | Media;
    featureHeadingBefore?: string | null;
    featureHeadingHighlight?: string | null;
    featureHeadingAfter?: string | null;
    featureParagraphs?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
  };
  classesSection?: {
    heading?: string | null;
    intro?: string | null;
  };
  contact?: {
    headingBefore?: string | null;
    headingHighlight?: string | null;
    headingAfter?: string | null;
    intro?: string | null;
    /**
     * Form submission URL. Leave the seeded FormSubmit URL or replace it with your own endpoint.
     */
    formAction?: string | null;
    namePlaceholder?: string | null;
    emailPlaceholder?: string | null;
    messagePlaceholder?: string | null;
    submitLabel?: string | null;
    requiredMessage?: string | null;
    invalidEmailMessage?: string | null;
    nameMaxLengthMessage?: string | null;
    messageMaxLengthMessage?: string | null;
    image?: (string | null) | Media;
  };
  footer?: {
    logo?: (string | null) | Media;
    description?: string | null;
    copyright?: string | null;
    linksHeading?: string | null;
    links?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    contactHeading?: string | null;
    contactText?: string | null;
    phone?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  navbar?:
    | T
    | {
        logo?: T;
        links?:
          | T
          | {
              label?: T;
              page?: T;
              id?: T;
            };
        signInLabel?: T;
        ctaLabel?: T;
      };
  home?:
    | T
    | {
        headlineImage?: T;
        body?: T;
        primaryCtaLabel?: T;
        secondaryCtaLabel?: T;
        heroImage?: T;
        sponsors?:
          | T
          | {
              name?: T;
              logo?: T;
              id?: T;
            };
      };
  benefits?:
    | T
    | {
        heading?: T;
        intro?: T;
        cards?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        cardCtaLabel?: T;
        featureImage?: T;
        featureHeadingBefore?: T;
        featureHeadingHighlight?: T;
        featureHeadingAfter?: T;
        featureParagraphs?:
          | T
          | {
              text?: T;
              id?: T;
            };
        ctaLabel?: T;
      };
  classesSection?:
    | T
    | {
        heading?: T;
        intro?: T;
      };
  contact?:
    | T
    | {
        headingBefore?: T;
        headingHighlight?: T;
        headingAfter?: T;
        intro?: T;
        formAction?: T;
        namePlaceholder?: T;
        emailPlaceholder?: T;
        messagePlaceholder?: T;
        submitLabel?: T;
        requiredMessage?: T;
        invalidEmailMessage?: T;
        nameMaxLengthMessage?: T;
        messageMaxLengthMessage?: T;
        image?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        description?: T;
        copyright?: T;
        linksHeading?: T;
        links?:
          | T
          | {
              label?: T;
              id?: T;
            };
        contactHeading?: T;
        contactText?: T;
        phone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}